config/routes.rb
SoilTestingKitSoftware::Application.routes.draw do
  
  root :to => 'soil_samples#index'
  match 'text_message/parse' => 'text_message#parse'
  resources :soil_samples
  
  match "soil_samples/:id" => "soil_samples#xss_options_request", :constraints => {:method => "OPTIONS"}
  

end

app/models/settings.rb
class Settings < Settingslogic
  source "#{Rails.root}/config/application.yml"
  namespace Rails.env
end

app/models/soil_sample.rb
class SoilSample < ActiveRecord::Base
  # TODO - change all this to use strong params
  attr_accessible :lat, :long, :moisture, :pH, :temperature, :time, :device_id, :comments, :device
  
  # TODO - Need to work this in to validate valus 
  
  # validates :lat, :numericality => true, :allow_blank => true   
  # validates :long, :numericality => true, :allow_blank => true  
  # validates :moisture, :numericality => true, :allow_blank => true  
  # validates :pH, :numericality => true, :allow_blank => true  
  # validates :temperature, :numericality => true, :allow_blank => true  
  # validates :time, :numericality => true, :allow_blank => true  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery
end

app/controllers/soil_samples_controller.rb
class SoilSamplesController < ApplicationController
  before_filter :allow_all
  after_filter :cors_preflight_check
  
  # HACKS
  def allow_all
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'GET, POST, OPTIONS, HEAD, PUT, DELETE'
    headers['Access-Control-Allow-Headers'] = '*,x-requested-with,Content-Type,If-Modified-Since,If-None-Match'

  end
  
  def cors_preflight_check
      headers['Access-Control-Allow-Origin'] = '*'
      headers['Access-Control-Allow-Methods'] = 'POST, GET, PUT, DELETE, OPTIONS'
      headers['Access-Control-Allow-Headers'] = 'X-Requested-With, X-Prototype-Version'
      headers['Access-Control-Max-Age'] = '1728000'
  end
  
  def xss_options_request
    render :text => ""
  end
  
  def index
   
      @soil_samples =  SoilSample.unscoped
      @soil_samples = @soil_samples.where(:device_id => params[:device_id])  if params[:device_id]
      @soil_samples = @soil_samples.where(:device => params[:device])  if params[:device]
      
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @soil_samples }
    end
  end
  
  def show
    @soil_sample = SoilSample.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @soil_sample }
    end
  end

  def new
    @soil_sample = SoilSample.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @soil_sample }
    end
  end

  # GET /soil_samples/1/edit
  def edit
    @soil_sample = SoilSample.find(params[:id])
  end

  def create
    puts params
    @soil_sample = SoilSample.new(params[:soil_sample])

    respond_to do |format|
      if @soil_sample.save
        format.html { redirect_to @soil_sample, notice: 'Soil sample was successfully created.' }
        format.json { render json: @soil_sample, status: :created, location: @soil_sample }
      else
        format.html { render action: "new" }
        format.json { render json: @soil_sample.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @soil_sample = SoilSample.find(params[:id])

    respond_to do |format|
      if @soil_sample.update_attributes(params[:soil_sample])
        format.html { redirect_to @soil_sample, notice: 'Soil sample was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @soil_sample.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @soil_sample = SoilSample.find(params[:id])
    @soil_sample.destroy

    respond_to do |format|
      format.html { redirect_to soil_samples_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/text_message_controller.rb
class TextMessageController < ApplicationController
  
  # further development, ability to localise into other languages
  # interact with the real API for growers nation
  
  # {"AccountSid"=>"AC0cbdc322dc58fddb8962e6062c7d8f48", 
  # "Body"=>"Ph 7.0", "ToZip"=>"", "FromState"=>"", "ToCity"=>"", 
  # "SmsSid"=>"SM55a7ffd250549828224e7fac39072745", "ToState"=>"Telford", "To"=>"+441952787011", 
  # "ToCountry"=>"GB", "FromCountry"=>"GB", "SmsMessageSid"=>"SM55a7ffd250549828224e7fac39072745", 
  # "ApiVersion"=>"2010-04-01", "FromCity"=>"", "SmsStatus"=>"received", "From"=>"+447818610137", "FromZip"=>"", 
  # "controller"=>"text_message", "action"=>"parse"}
  
    # t.float    "ph"
    # t.float    "longitude"
    # t.float    "latitude"
    # t.float    "moisture"
    # t.float    "temperature"
  
  # make into service
  
  def parse
    @original_message = message = params[:Body] + ' '
    
    if message.blank? || message =~ /\Ainfo\s*\z|start/i
      render 'instructions.xml.erb', :content_type => 'text/xml' and return
    elsif message =~ /\Ainfo\s+([A-z]+)\s+([A-z0-9.=\s]+)/i 
      crop = $1
      options = $2
      request_information(crop, options)
    else
      # check if sending data
      process_sample_data(message)
    end
  end
  
  def request_information(crop, options)
    @crop = crop
    @options_hash = MessageParser.string_to_hash(options)
    if  @options_hash.length == 2 && @options_hash.include?('long') && @options_hash.include?('long')
      # hit external service for data then send back
      render 'crop_info.xml.erb', :content_type => 'text/xml' and return
    else
      render 'incorrect_format.xml.erb', :content_type => 'text/xml' and return
    end
  end
  
  def process_sample_data(readings)
    # ph=7.9,temp=31.3,lat=51.112,long=52.1223,moisture=21 
    readings_hash = MessageParser.string_to_hash(readings)
    # send to external service for now save to out DB
    @sample = set_soil_params(readings_hash)
    
    if @sample
      render 'successful_sample.xml.erb', :content_type => 'text/xml' and return
    else
      render 'unknown_command.xml.erb', :content_type => 'text/xml' and return
    end
  end
  
  # dirty make tidyier
  # move into model
  def set_soil_params(params)
    sample = SoilSample.new
    params.each do |key, value|
      case key
        when /pH/i
          sample.pH = value
        when /temp|temperature/i
          sample.temperature = value
        when /long|longitude/i
          sample.long = value
        when /lat|latitude/i
          sample.lat = value
        when /moisture|mois/i
          sample.moisture = value 
      end
    end
    
    if sample.changed?
      sample.device_id = '01234567822'
      sample.device = 'phone'
      if sample.save
        return sample
      else
        return false
      end
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/soil_samples_helper.rb
module SoilSamplesHelper
end

app/helpers/text_message_helper.rb
module TextMessageHelper
  def format_sample(sample)
    sample.attributes.map{|k,v| "#{k}: #{v}" unless v.blank? || k =~ /updated_at|created_at/}.compact.join(' ')
  end
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SoilTestingKitSoftware</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/soil_samples/_form.html.erb
<%= form_for(@soil_sample) do |f| %>
  <% if @soil_sample.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@soil_sample.errors.count, "error") %> prohibited this soil_sample from being saved:</h2>

      <ul>
      <% @soil_sample.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/soil_samples/edit.html.erb
<h1>Editing soil_sample</h1>

<%= render 'form' %>

<%= link_to 'Show', @soil_sample %> |
<%= link_to 'Back', soil_samples_path %>

app/views/soil_samples/index.html.erb
<h1>Listing soil_samples</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @soil_samples.each do |soil_sample| %>
  <tr>
    <td><%= link_to 'Show', soil_sample %></td>
    <td><%= link_to 'Edit', edit_soil_sample_path(soil_sample) %></td>
    <td><%= link_to 'Destroy', soil_sample, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Soil sample', new_soil_sample_path %>

app/views/soil_samples/new.html.erb
<h1>New soil_sample</h1>

<%= render 'form' %>

<%= link_to 'Back', soil_samples_path %>

app/views/soil_samples/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_soil_sample_path(@soil_sample) %> |
<%= link_to 'Back', soil_samples_path %>

app/views/text_message/crop_info.xml.erb
<Response>
  <Sms><%= @crop %> at <%= @options_hash.map{|k,v| "#{k}: #{v}"}.join(' ') %>. Plant in the spring, harvest in the autumn</Sms>
</Response>

app/views/text_message/failure.xml.erb
<Response>
  <Sms>Uh Oh Something went wrong</Sms>
</Response>

app/views/text_message/incorrect_format.xml.erb
<Response>
  <Sms><%= @original_message %> is Incorrect Format - info corn long=54.22 lat=23.33</Sms>
</Response>

app/views/text_message/instructions.xml.erb
<Response>
  <Sms>Send any readings for temp, ph, long, lat, moisture eg temp=37, ph=8.9 etc..</Sms>
</Response>

app/views/text_message/successful_sample.xml.erb
<Response>
  <Sms>Readings saved with <%= format_sample(@sample) %></Sms>
</Response>

app/views/text_message/unknown_command.xml.erb
<Response>
  <Sms>Uh Oh Something went wrong</Sms>
</Response>